const axios = require('axios');
const papa = require('papaparse');
const fs = require('fs');

const filePath = 'src/modules/walle/resources/walle.generate.ts';

const CSV_FILE = 'https://docs.google.com/spreadsheets/d/19Kq4FNRxRojCDajOtSCdS38d_cSB_MZnXRY0Od-tDig/pub?gid=0&single=true&output=csv';

axios.get(CSV_FILE).then(res => {
  const csvInfo = papa.parse(res.data);

  const tableHaed = csvInfo.data[0]; // [ '編號(id)', '辯題(name)', '類別(category)', '備註' ]
  const idIndex = tableHaed.findIndex(key => key.includes('id'));
  const nameIndex = tableHaed.findIndex(key => key.includes('name'));
  const categoryIndex = tableHaed.findIndex(key => key.includes('category'));

  // 移除表頭、空白資料
  const tableBody = csvInfo.data.filter((item, index) => index !== 0 && item[idIndex] !== '');
  
  // 找出 'walle-complete' 和 'walle-combined' 的 index
  const walleCompleteIndex = tableBody.findIndex(row => row[idIndex] === 'walle-complete');
  const walleCombinedIndex = tableBody.findIndex(row => row[idIndex] === 'walle-combined');

  const createWalleItem = (item) => ({
    id: item[idIndex],
    content: item[nameIndex],
    category: item[categoryIndex],
  });

  // 截取内容
  const walleComplete = tableBody.slice(walleCompleteIndex + 1, walleCombinedIndex).map(createWalleItem);
  const walleCombined = tableBody.slice(walleCombinedIndex + 1).map(createWalleItem);


  fs.writeFileSync(
    filePath,
    `// Code generated by create-walle.cjs, DO NOT EDIT.
// You can use 'pnpm create-walle'.

export const DEFAULT_WALLE_COMPLETE_FROM_CSV = ${JSON.stringify(walleComplete, null, '  ')};

export const DEFAULT_WALLE_COMBINED_FROM_CSV = ${JSON.stringify(walleCombined, null, '  ')};
`,
    'utf8',
  );
});
