// Code generated by create-ga-config.cjs, DO NOT EDIT.
// You can use 'pnpm ga-config'.

const GA_EVENT_STRING = {
  "Header_Button_To_Timers": {
    "category": "Header",
    "action": "click",
    "label": "頁首:前往「計時器列表」"
  },
  "Header_Button_Add_Timer": {
    "category": "Header",
    "action": "click",
    "label": "頁首:新增「計時器」"
  },
  "Header_Button_To_Dummys": {
    "category": "Header",
    "action": "click",
    "label": "頁首:前往「攻防組列表」"
  },
  "Header_Button_Add_Dummy": {
    "category": "Header",
    "action": "click",
    "label": "頁首:新增「攻防組」"
  },
  "Header_Button_To_Walles": {
    "category": "Header",
    "action": "click",
    "label": "頁首:前往「抽題器列表」"
  },
  "Header_Button_Add_Walle": {
    "category": "Header",
    "action": "click",
    "label": "頁首:新增「抽題器」"
  },
  "Header_Button_Listenings": {
    "category": "Header",
    "action": "click",
    "label": "頁首:前往「戰場判斷列表」"
  },
  "Header_Button_Add_Listening": {
    "category": "Header",
    "action": "click",
    "label": "頁首:新增「戰場判斷表」"
  },
  "Header_Button_Menu": {
    "category": "Header",
    "action": "click",
    "label": "頁首:打開「側欄選單」"
  },
  "Menu_Item_To_Timer": {
    "category": "Menu",
    "action": "click",
    "label": "側欄選單:前往「計時器」"
  },
  "Menu_Item_To_Walle": {
    "category": "Menu",
    "action": "click",
    "label": "側欄選單:前往「抽題器」"
  },
  "Menu_Item_To_Dummy": {
    "category": "Menu",
    "action": "click",
    "label": "側欄選單:前往「攻防組」"
  },
  "Timers_Button_View_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "計時器列表:查看「計時器」"
  },
  "Timers_Button_Add_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "計時器列表:新增「計時器」"
  },
  "Timers_Button_Edit_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "計時器列表:編輯「計時器」"
  },
  "Timers_Button_Delete_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "計時器列表:刪除「計時器」"
  },
  "TimerEditor_Button_Save": {
    "category": "TimerEditor",
    "action": "submit",
    "label": "計時器編輯器:儲存「計時器」"
  },
  "TimerEditor_Button_Setting": {
    "category": "TimerEditor",
    "action": "click",
    "label": "計時器編輯器:打開「進階設定」"
  },
  "Timer_Button_Play": {
    "category": "Timer",
    "action": "click",
    "label": "計時器:開始計時"
  },
  "Dummys_Button_View_Dummy": {
    "category": "Dummys",
    "action": "click",
    "label": "攻防組列表:查看「攻防組」"
  },
  "Dummys_Button_Add_Dummy": {
    "category": "Dummys",
    "action": "click",
    "label": "攻防組列表:新增「攻防組」"
  },
  "Dummys_Button_Edit_Dummy": {
    "category": "Dummys",
    "action": "click",
    "label": "攻防組列表:編輯「攻防組」"
  },
  "Dummys_Button_Delete_Dummy": {
    "category": "Dummys",
    "action": "click",
    "label": "攻防組列表:刪除「攻防組」"
  },
  "DummyEditor_Button_Save": {
    "category": "DummyEditor",
    "action": "submit",
    "label": "攻防組編輯器:儲存「攻防組」"
  },
  "DummyEditor_Button_Copy_Dummy": {
    "category": "DummyEditor",
    "action": "click",
    "label": "攻防組編輯器:複製「攻防組」內容"
  },
  "Dummy_Button_Spin_DummyContent": {
    "category": "Dummy",
    "action": "click",
    "label": "抽題器:抽出「攻防子項」"
  },
  "Walles_Button_View_Walle": {
    "category": "Walles",
    "action": "click",
    "label": "抽題器列表:查看「抽題器」"
  },
  "Walles_Button_Add_Walle": {
    "category": "Walles",
    "action": "click",
    "label": "抽題器列表:新增「抽題器」"
  },
  "Walles_Button_Edit_Walle": {
    "category": "Walles",
    "action": "click",
    "label": "抽題器列表:編輯「抽題器」"
  },
  "Walles_Button_Delete_Walle": {
    "category": "Walles",
    "action": "click",
    "label": "抽題器列表:刪除「抽題器」"
  },
  "WalleEditor_Button_Save": {
    "category": "WalleEditor",
    "action": "submit",
    "label": "抽題器編輯器:儲存「抽題器」"
  },
  "WalleEditor_Button_Copy_Walle": {
    "category": "WalleEditor",
    "action": "click",
    "label": "抽題器編輯器:複製「抽題器」內容"
  },
  "Walle_Button_Spin_WalleContent": {
    "category": "Walle",
    "action": "click",
    "label": "抽題器:抽出「辯題選項」"
  },
  "Walle_Button_TopicMiddleItemMode_Causal": {
    "category": "Walle",
    "action": "click",
    "label": "抽題器:切換「因果型辯題」"
  },
  "Walle_Button_TopicMiddleItemMode_Compare": {
    "category": "Walle",
    "action": "click",
    "label": "抽題器:切換「比較型辯題」"
  },
  "SideDrawer_Button_Draw": {
    "category": "SideDrawer",
    "action": "click",
    "label": "持方抽選器:抽出「持方」"
  },
  "ResultPicker_Button_Judge": {
    "category": "ResultPicker",
    "action": "click",
    "label": "判決器:判決「勝方」"
  },
  "TopicListDrawer_Button_Settting": {
    "category": "TopicListDrawer",
    "action": "click",
    "label": "點擊辯題列表彈窗「進階設定」按鈕"
  },
  "Listenings_Button_Edit_Listening": {
    "category": "Listenings",
    "action": "click",
    "label": "點擊戰場判斷列表「編輯戰場判斷表」按鈕＋「戰場判斷表名稱_擁有者」"
  },
  "Listenings_Button_Delete_Listening": {
    "category": "Listenings",
    "action": "click",
    "label": "點擊戰場判斷列表「刪除戰場判斷表」按鈕"
  }
};
export default GA_EVENT_STRING;
