// Code generated by create-ga-config.cjs, DO NOT EDIT.
// You can use 'pnpm ga-config'.
const GA_EVENT_STRING = {
  "Header_Button_Timers": {
    "category": "Header",
    "action": "click",
    "label": "Header_Button_Timers"
  },
  "Header_Button_Add_Timer": {
    "category": "Header",
    "action": "click",
    "label": "Header_Button_Add_Timer"
  },
  "Header_Button_Listenings": {
    "category": "Header",
    "action": "click",
    "label": "Header_Button_Listenings"
  },
  "Header_Button_Add_Listening": {
    "category": "Header",
    "action": "click",
    "label": "Header_Button_Add_Listening"
  },
  "Header_Button_Menu": {
    "category": "Header",
    "action": "click",
    "label": "Header_Button_Menu"
  },
  "Menu_Item_To_Timer": {
    "category": "Menu",
    "action": "click",
    "label": "Menu_Item_To_Timer"
  },
  "Menu_Item_To_TopicCreator": {
    "category": "Menu",
    "action": "click",
    "label": "Menu_Item_To_TopicCreator"
  },
  "Timer_Button_Play": {
    "category": "Timer",
    "action": "click",
    "label": "Timer_Button_Play"
  },
  "Timers_Item_To_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "Timers_Item_To_Timer"
  },
  "Timers_Button_Edit_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "Timers_Button_Edit_Timer"
  },
  "Timers_Button_Delete_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "Timers_Button_Delete_Timer"
  },
  "TimersEditor_Button_Submit": {
    "category": "TimerEditor",
    "action": "submit",
    "label": "TimersEditor_Button_Submit"
  },
  "TimersEditor_Button_Settting": {
    "category": "TimerEditor",
    "action": "click",
    "label": "TimersEditor_Button_Settting"
  },
  "TopicCreator_Button_TopicMode_Complete": {
    "category": "TopicCreator",
    "action": "click",
    "label": "TopicCreator_Button_TopicMode_Complete"
  },
  "TopicCreator_Button_TopicMode_Combined": {
    "category": "TopicCreator",
    "action": "click",
    "label": "TopicCreator_Button_TopicMode_Combined"
  },
  "TopicCreator_Button_TopicMiddleItemMode_Causal": {
    "category": "TopicCreator",
    "action": "click",
    "label": "TopicCreator_Button_TopicMiddleItemMode_Causal"
  },
  "TopicCreator_Button_TopicMiddleItemMode_Compare": {
    "category": "TopicCreator",
    "action": "click",
    "label": "TopicCreator_Button_TopicMiddleItemMode_Compare"
  },
  "TopicCreator_Button_SpinTopic": {
    "category": "TopicCreator",
    "action": "click",
    "label": "TopicCreator_Button_SpinTopic"
  },
  "TopicDrawer_Button_Draw": {
    "category": "TopicDrawer",
    "action": "click",
    "label": "TopicDrawer_Button_Draw"
  },
  "ResultPicker_Button_Judge": {
    "category": "ResultPicker",
    "action": "click",
    "label": "ResultPicker_Button_Judge"
  },
  "TopicListDrawer_Button_Settting": {
    "category": "TopicListDrawer",
    "action": "click",
    "label": "TopicListDrawer_Button_Settting"
  },
  "Listenings_Button_Edit_Listening": {
    "category": "Listenings",
    "action": "click",
    "label": "Listenings_Button_Edit_Listening"
  },
  "Listenings_Button_Delete_Listening": {
    "category": "Listenings",
    "action": "click",
    "label": "Listenings_Button_Delete_Listening"
  }
};
export default GA_EVENT_STRING;
